[workspace]
resolver = "2"
members = [
  "ivy-utils",
  "ivy-syntax",
  "ivy-parse",
  "ivy-types",
  "ivy-eval",
  "ivy",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "BSD-3-Clause"
authors = ["Gerardo Torres Castro"]

[workspace.lints.clippy]
absolute_paths = "deny"
or_fun_call = "deny"
large_futures = "deny"
cast_lossless = "warn"
semicolon_if_nothing_returned = "warn"
implicit_clone = "warn"
inconsistent_struct_constructor = "warn"
needless_pass_by_value = "warn"
trivially_copy_pass_by_ref = "warn"
manual_assert = "warn"
cloned_instead_of_copied = "warn"
redundant_closure_for_method_calls = "warn"
manual_let_else = "warn"
unnested_or_patterns = "warn"
ref_option = "warn"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.dependencies]
ivy-utils = { path = "ivy-utils" }
ivy-syntax = { path = "ivy-syntax" }
ivy-parse = { path = "ivy-parse" }
ivy-types = { path = "ivy-types" }
ivy-eval = { path = "ivy-eval" }
thiserror = "2"
miette = { version = "7", features = ["fancy"] }
colored = "2"
rustyline = "14"
rand = "0.8"
