[package]
name = "ivy-types"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Type system for the Ivy programming language"

[lints]
workspace = true

[dependencies]
ivy-syntax.workspace = true
ivy-parse.workspace = true
thiserror.workspace = true
miette.workspace = true
